server.port=9090
server.address=0.0.0.0

spring.main.lazy-initialization=true
spring.main.banner-mode=off

spring.sql.init.mode=always
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://postgres:5432/shareit
spring.datasource.username=shareit
spring.datasource.password=shareit

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.health.db.enabled=true

logging.level.root=WARN
logging.level.ru.practicum.shareit=INFO
logging.level.org.springframework.boot=INFO
logging.level.org.springframework.web=ERROR
logging.level.org.hibernate=ERROR