DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users (
                                     id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name  VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS items (
                                     id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name         VARCHAR(255) NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id     BIGINT REFERENCES users(id) ON DELETE CASCADE,
    request_id   BIGINT
    );

CREATE TABLE IF NOT EXISTS bookings (
                                        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        end_date   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                        item_id    BIGINT REFERENCES items(id) ON DELETE CASCADE,
    booker_id  BIGINT REFERENCES users(id) ON DELETE CASCADE,
    status     VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS comments (
                                        id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        text      VARCHAR(1000) NOT NULL,
    item_id   BIGINT REFERENCES items(id) ON DELETE CASCADE,
    author_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    created   TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE TABLE IF NOT EXISTS requests (
                                        id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                        description  VARCHAR(1000) NOT NULL,
    requester_id BIGINT NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requests_requester_id FOREIGN KEY (requester_id) REFERENCES users (id)
    );

ALTER TABLE items ADD CONSTRAINT fk_items_request_id FOREIGN KEY (request_id) REFERENCES requests (id);